### ISSUE TITLE
Kyma 1.14: deployment of orders-list-api.yaml fails

### ISSUE THREAD

**Issue by rolpat** [jcawley5/oidc-sample-app#1]
Hi!
Unfortunately the deployment of orders-list-api.yaml fails with the error 
```
Error from server (BadRequest): error when creating "oidc-sample-app/kyma/orders-list-api.yaml": admission webhook "defaulting.webhook.serverless.kyma-project.io" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "functionContentType"
```
According to the [documentation](https://kyma-project.io/docs/components/serverless/) the CR does not support the attributes spec.runtime and spec.functionContentType any more. 

Workaround: 
by deleting both attributes in the manifest the deployment works and the default values are used which should be ok here as far as I see.
 
Thanks!

**Comment by jcawley5** [comment]
Thank you for pointing this out.  I have updated the definition accordingly.
